# CMake generated Testfile for 
# Source directory: D:/ncnn_win32/tests
# Build directory: D:/ncnn_win32/builds/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_batchnorm "test_batchnorm")
set_tests_properties(test_batchnorm PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;20;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_binaryop "test_binaryop")
set_tests_properties(test_binaryop PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;21;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_cast "test_cast")
set_tests_properties(test_cast PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;22;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_clip "test_clip")
set_tests_properties(test_clip PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;23;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_concat "test_concat")
set_tests_properties(test_concat PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;24;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_convolution "test_convolution")
set_tests_properties(test_convolution PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;25;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_convolutiondepthwise "test_convolutiondepthwise")
set_tests_properties(test_convolutiondepthwise PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;26;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_crop "test_crop")
set_tests_properties(test_crop PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;27;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_deconvolution "test_deconvolution")
set_tests_properties(test_deconvolution PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;28;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_deconvolutiondepthwise "test_deconvolutiondepthwise")
set_tests_properties(test_deconvolutiondepthwise PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;29;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_deepcopy "test_deepcopy")
set_tests_properties(test_deepcopy PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;30;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_dropout "test_dropout")
set_tests_properties(test_dropout PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;31;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_eltwise "test_eltwise")
set_tests_properties(test_eltwise PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;32;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_elu "test_elu")
set_tests_properties(test_elu PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;33;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_flatten "test_flatten")
set_tests_properties(test_flatten PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;34;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_hardsigmoid "test_hardsigmoid")
set_tests_properties(test_hardsigmoid PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;35;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_hardswish "test_hardswish")
set_tests_properties(test_hardswish PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;36;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_innerproduct "test_innerproduct")
set_tests_properties(test_innerproduct PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;37;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_instancenorm "test_instancenorm")
set_tests_properties(test_instancenorm PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;38;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_interp "test_interp")
set_tests_properties(test_interp PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;39;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_lrn "test_lrn")
set_tests_properties(test_lrn PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;40;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_memorydata "test_memorydata")
set_tests_properties(test_memorydata PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;41;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_noop "test_noop")
set_tests_properties(test_noop PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;42;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_normalize "test_normalize")
set_tests_properties(test_normalize PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;43;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_packing "test_packing")
set_tests_properties(test_packing PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;44;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_padding "test_padding")
set_tests_properties(test_padding PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;45;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_permute "test_permute")
set_tests_properties(test_permute PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;46;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_pixelshuffle "test_pixelshuffle")
set_tests_properties(test_pixelshuffle PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;47;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_pooling "test_pooling")
set_tests_properties(test_pooling PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;48;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_prelu "test_prelu")
set_tests_properties(test_prelu PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;49;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_roipooling "test_roipooling")
set_tests_properties(test_roipooling PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;50;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_relu "test_relu")
set_tests_properties(test_relu PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;51;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_reorg "test_reorg")
set_tests_properties(test_reorg PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;52;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_reshape "test_reshape")
set_tests_properties(test_reshape PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;53;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_scale "test_scale")
set_tests_properties(test_scale PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;54;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_shufflechannel "test_shufflechannel")
set_tests_properties(test_shufflechannel PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;55;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_sigmoid "test_sigmoid")
set_tests_properties(test_sigmoid PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;56;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_slice "test_slice")
set_tests_properties(test_slice PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;57;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_softmax "test_softmax")
set_tests_properties(test_softmax PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;58;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_tanh "test_tanh")
set_tests_properties(test_tanh PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;59;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_unaryop "test_unaryop")
set_tests_properties(test_unaryop PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;60;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
add_test(test_mish "test_mish")
set_tests_properties(test_mish PROPERTIES  _BACKTRACE_TRIPLES "D:/ncnn_win32/tests/CMakeLists.txt;9;add_test;D:/ncnn_win32/tests/CMakeLists.txt;61;ncnn_add_layer_test;D:/ncnn_win32/tests/CMakeLists.txt;0;")
